#!/usr/bin/env bash

#- Version: 1.0
#- Author: Enrico Spinielli
#- Date: 2015/03/12
#- Copyright (C) 2015 Eurocontrol/PRU

## Usage: airac [YYYY-MM-DD]
## Print the current AIRAC in both CFMU anf standard format for today or
## for YYYY-MM-DD if provided.
## 
## Arguments:
##   YYYY-MM-DD              a data, i.e. 2013-07-01
## 
## Options:
##   -h, --help              Print a usage message summarizing the command-line options, then exit.
##   -V, --version           Output version information and exit.
## 
## 
## Examples:
## 
## $ airac
## Days in AIRAC = 7
## Start of AIRAC = 2015-03-05
## Number of AIRACs since 310/0807 (2008-07-03) = 87
## (CFMU) AIRAC = 397
## 
## $ airac 2013-07-01
## Days in AIRAC = 4
## Start of AIRAC = 2013-06-27
## Number of AIRACs since 310/0807 (2008-07-03) = 65
## (CFMU) AIRAC = 375

SCRIPT=$(basename ${BASH_SOURCE[0]})

help=$(grep "^## " "${SCRIPT}" | cut -c 4-)
version=$(grep "^#- " "${SCRIPT}" | cut -c 4-)
opt_h() {
  echo "$help"
}
 
opt_v() {
  echo "$version"
}

# Execute getopt (-n reports  SCRIPT as the source of errors and not getopt)
TEMP=$(getopt -o :hVd: -l help,version,date -n "$SCRIPT" -- "$@");
eval set -- "$TEMP"

while true; do
   case $1 in
   -h | --help)
      opt_h
      exit
      ;;
   -V | --version)
      opt_v
      exit
      ;;
   -d | --date)
      case "$2" in
      "") shift 2 ;;
      *) today=$(date -ud "$2" "+%s") ; shift 2 ;;
      esac ;;
   --)
      shift
      break
      ;;
   \?)
      echo "Invalid option: -$OPTARG" >&2
      opt_h
      exit 1
      ;;
   *)
      echo "Internal error!"
      exit 1
      ;;
   esac
done

# in seconds ()
REF_DATE=$(date -ud "2008-07-03" +"%s")
REF_CFMU=310
REF_STD=0807
WEEKS_IN_AIRAC=4

# there is 1 optional argument

if (( $# == 1 )); then
   # generate the airac info for the specified date
   today=${today-$(date -ud "$(date -ud "$1" +"%Y-%m-%d")" +"%s")}
elif (( $# > 1 ))
then
   # error
   echo "Error: too many arguments."
   opt_h
   exit 1
else
   today=${today-$(date -ud "$(date -ud "$1" +"%Y-%m-%d")" +"%s")}
fi

today=${today-$(date -ud "$(date -ud "today" +"%Y-%m-%d")" +"%s")}

days_in_airac=$(( (( $today - $REF_DATE) / (24*3600)) % (7 * $WEEKS_IN_AIRAC) )) 
secs_in_airac=$(( $days_in_airac * 24 * 60 * 60 ))
airacs_since=$(( ($today - $REF_DATE - $days_in_airac ) / (24*3600) / 7 / $WEEKS_IN_AIRAC ))
start_of_airac=$(( $today - $secs_in_airac ))

echo "Days in AIRAC = $days_in_airac"
echo "Start of AIRAC = $(date -u -d "$(date -u -d "@$start_of_airac" "+%F")" "+%F")"
echo "Number of AIRACs since $REF_CFMU/$REF_STD ($(date -d "@$REF_DATE" +"%F")) = $airacs_since"
echo "(CFMU) AIRAC = $(( $REF_CFMU + $airacs_since ))"
